//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Embarques {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class ConsDetEmb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsDetEmb() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Embarques.ConsDetEmb", typeof(ConsDetEmb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool CANT_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CANT.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool FECHACAD_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("FECHACAD.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool LOTE_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("LOTE.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool PESO_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("PESO.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool PesoCaja_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("PesoCaja.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool PESOXCJ_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("PESOXCJ.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool SSCC_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("SSCC.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool TEMP_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("TEMP.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool TIPOREC_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("TIPOREC.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool UBICA_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("UBICA.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
